export enum ERoute {
  UserLogin = '/user/login',
  UserSignup = '/user/signup',
  UserEdit = '/user/edit',
  UserPasswordReset = '/user/password/reset',
  IntroAbout = '/intro/about',
  IntroPeople = '/intro/people',
  IntroHistory = '/intro/history',
  IntroSettlement = '/intro/settlement',
  IntroLocation = '/intro/location',
  ActivityNotice = '/activity/notice',
  ActivityAction = '/activity/action',
  ActivityPress = '/activity/press',
  AffiliateAbout = '/affiliate/about',
  AffiliateActivity = '/affiliate/activity',
  MemberSocietyAbout = '/member/society_about',
  MemberSocietyActivity = '/member/society_activity',
  MemberLocal = '/member/local',
  MemberDonation = '/member/donation',
  MemberBand = '/member/band',
  BulletinNewsletter = '/bulletin/newsletter',
  BulletinGallery = '/bulletin/gallery',
}
