export enum ERoute {
  UserLogin = '/user/login',
  UserSignup = '/user/signup',
  UserEdit = '/user/edit',
  UserPasswordReset = '/user/password/reset',
  UserActivate = '/user/activate',
  PasswordUpdate = '/password/update',
  IntroAbout = '/intro/about',
  IntroPeople = '/intro/people',
  IntroHistory = '/intro/history',
  IntroSettlement = '/intro/settlement',
  IntroLocation = '/intro/location',
  ActivityNotice = '/activity/notice',
  ActivityAction = '/activity/action',
  ActivityPress = '/activity/press',
  ActivityMember = '/activity/member',
  ActivityDonation = '/activity/donation',
  ActivityDonationStep = '/activity/donation/step',
  ActivityCalendar = '/activity/calendar',
  AffiliateAbout = '/affiliate/about',
  AffiliateActivity = '/affiliate/activity',
  MemberSocietyAbout = '/member/society_about',
  MemberSocietyActivity = '/member/society_activity',
  MemberSpace = '/member/space',
  BulletinNewsletter = '/bulletin/newsletter',
  BulletinGallery = '/bulletin/gallery',
  BulletinDrive = '/bulletin/drive',
  IntranetShare = '/intranet/share',
  IntranetDrive = '/intranet/drive',
  IntranetGeneral = '/intranet/general',
  Privacy = '/privacy',
  Agreement = '/agreement',
}

export enum EMessageID {
  SignupSuccess = 'signup_success',
  ActivateSuccess = 'activate_success',
  PasswordUpdate = 'password_update',
  PasswordReset = 'password_reset',
  BoardDelete = 'board_delete',
  BoardCreate = 'board_create',
  BoardEdit = 'board_edit',
}

